import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_SA': {
          'login': 'تسجيل الدخول',
          'setting': 'الإعدادات',
          'nodata': 'لا توجد بيانات',
          'miles': 'كيلو متر',
          'cardetails': 'تفاصيل السيارة',
          "Auctions": "المزادات",
          "Home": "الرئيسية",
          "Notifications": "الاشعارات",
          "Help": "المساعدة",
          "UserName": "اسم المستخدم",
          "Verified": "تم التحقق",
          "Dealer": "تاجر",
          "Total vehicles": "مجموع المركبات",
          "Hosted Auction": "المزاد المستضاف",
          "Participated": "شارك",
          "About Us": "معلومات عنا",
          "Settings": "إعدادات",
          "Add Car": "اضافة سيارة",
          "Logout": "تسجيل خروج",
          "Sing in": "تسجيل الدخول",
          "Sing Up": "التسجيل",
          "Email": "بريد إلكتروني",
          "Password": "كلمة المرور",
          "Sign In Using": "تسجيل الدخول باستخدام",
          "Name": "الاسم",
          "Confirm Password": "تأكيد كلمة المرور",
          "Won Auctions": "فاز بالمزادات",
          "Out bid Auction": "المزاد العلني",
          "There is no Won Cars yet": "لا توجد سيارات كسبتها حتى الان",
          "There is no Out bid Cars": "لا يوجد سيارات زايدت عليها حتى الان",
          "There is no Notifications": "لا توجد إشعارات",
          "User Profile": "ملف تعريفي للمستخدم",
          "Change Password": "تغيير كلمة المرور",
          "Change Phone": "تغيير الهاتف",
          "TermsCondition": "الشروط والأحكام",
          "Current Password": "كلمة المرور الحالية",
          "New Password": "كلمة المرور الجديدة",
          "Confirm New Password": "تأكيد كلمة المرور الجديدة",
          "Save": "حفظ",
          "Enter Your Phone": "أدخل هاتفك",
          "Next": "التالى",
          "Sms Notification": "إعلام الرسائل القصيرة",
          "Normal Auctions": "مزادات عادية",
          "No Reserve Auctions": "لا توجد مزادات احتياطية",
          "Buy Now Auctions": "اشتر الآن المزادات",
          "Out Bidding": "المزايدة",
          "Gallery": "المعرض",
          "Camera": "الكاميرا",
          "First Name": "الاسم الأول",
          "Last Name": "اسم العائلة",
          "State": "ولاية",
          "City": "مدينة",
          "Zip": "الرمز البريدي",
          "Update": "تعديل",
          "Car details": "تفاصيل السيارة",
          "Components Summary": "ملخص المكونات",
          "Interior": "الداخلية",
          "Exterior": "الخارج",
          "For Help": "للمساعدة",
          "PLACE A BID": "ضع مزايدة",
          'Make': 'مصنع',
          'Model': 'سنة الصنع',
          'Year': 'سنة',
          'Mileage': 'عدد الاميال',
          'Specification': 'مواصفات',
          'Body Type': 'نوع الجسم',
          'Engine Size': 'حجم المحرك',
          'Service History': 'سجل الخدمة',
          'Warranty': 'ضمان',
          'Engine Condition': 'حالة المحرك',
          'Transmission': 'جهاز نقل الحركة',
          'Mortgage': 'القرض العقاري',
          'Number of Keys': 'عدد المفاتيح',
          'Central locking': 'قفل مركزي',
          'Tires': 'الإطارات',
          'Steering': 'قيادة',
          'Engine': 'محرك',
          'Gearbox': 'ناقل الحركة',
          'Dash Lights': 'مصابيح داش',
          'Electric Component': 'مكون كهربائي',
          'Ac/Heating': 'تكييف / تدفئة',
          'Breaks': 'فرامل',
          'Suspension': 'تعليق',
          'Exhaust': 'العادم',
          'Clutch': 'القابض',
          'Windows Sunroof': 'فتحة سقف نوافذ',
          'Central Locking': 'قفل مركزي',
          'Horn Light Radio': 'راديو هورن لايت',
          'Seats': 'مقاعد',
          'Navigation': 'الملاحة',
          'Sunroof': 'فتحة سقف',
          'Interior Color': 'اللون الداخلي',
          'Comment': 'تعليق',
          'Front Bumper': 'المصد الأمامي',
          'Rear Bumper': 'الصدام الخلفي',
          'Bonnet': 'غطاء محرك السيارة',
          'Roof': 'سَطح',
          'Boot Trunk': 'صندوق التمهيد',
          'Driver Side Front Wing': 'الجناح الأمامي للسائق',
          'Driver Side Front Door': 'الباب الأمامي للسائق',
          'Driver Side Rear Door': 'الباب الخلفي للسائق',
          'Driver Side Rear Quarter': 'سائق الجانب الخلفي الربع',
          'Passenger Side Front Wing': 'الجناح الأمامي للركاب',
          'Passenger Side Front Door': 'الباب الأمامي للركاب',
          'Passenger Side Rear Door': 'الباب الخلفي للراكب',
          'Passenger Side Rear Quarter': 'الربع الخلفي جانب الركاب',
          'Driver Side Front Tyre': 'سائق جانب الجبهة الاطارات',
          'Driver Side Rear Tyre': 'جانب السائق الاطارات الخلفية',
          'Passenger Side Front Tyre': 'جانب الراكب الامامي الاطارات',
          'Passenger Side Rear Tyre': 'الراكب الاطارات الخلفية',
          'Blue': 'ازرق',
          'Faded': 'باهتة',
          'Red': 'احمر',
          'Painted': 'مدهون',
          'White': 'ابيض',
          'Original': 'اصلى',
          'Yellow': 'اصفر',
          'Smart Paint': 'الطلاء الذكي',
          'Live Auction': 'المزاد المباشر',
          'Auction': 'المزاد',
          'CustomerPrice': 'سعر للعميل',
          'Vat Value': 'القيمة المضافة',
          'Starting Bid': 'بداية المزايدة',
          'Current Bid': 'المزايدة الحالية',
          'Total Bids': 'اجمالى المزايدات',
          'Your Last Bid': 'قيمة اخر مزايدة لك',
          'Enter Price': 'ادخل السعر',
          'Clear': 'مسح',
          'PLace Bid': 'ضع مزايدة',
          'Bidder': 'العارض',
          'Amount': 'كمية',
          'Time': 'وقت',
          'Add Car': 'اضافة سيارة',
          'Add from Gallery': 'أضف من المعرض',
          'Add from Camera': 'أضف من الكاميرا',
          'Color': 'اللون',
          'Enter Car Mileage': 'ادخل عدد الاميال',
          'Next': 'التالى',
          'Select': 'اختر',
          'Type': 'النوع',
          'Submit for Auction': 'أرسل للمزاد',
          'Live':'المباشـر',
          'All Cars':'الكــــل'
        },
        'en_US': {
          'setting': 'Settings',
          'nodata': 'Empty data',
          'miles': 'KMs',
          'cardetails': 'Car details',
          "Auctions": "Auctions",
          "Home": "Home",
          "Notifications": "Notifications",
          "Help": "Help",
          "UserName": "UserName",
          "Verified": "Verified",
          "Dealer": "Dealer",
          "Total vehicles": "Total vehicles",
          "Hosted Auction": "Hosted Auction",
          "Participated": "Participated",
          "About Us": "About Us",
          "Settings": "Settings",
          "Add Car": "Add Car",
          "Logout": "Logout",

          "Sing in": "Sing in",
          "Sing Up": "Sing Up",
          "Email": "Email",
          "Password": "Password",
          "Sign In Using": "Sign In Using",
          "Name": "Name",
          "Confirm Password": "Confirm Password",
          "Won Auctions": "Won Auctions",
          "Out bid Auction": "Out bid Auction",
          "There is no Won Cars yet": "There is no Won Cars yet",
          "There is no Out bid Cars": "There is no Out bid Cars",
          "There is no Notifications": "There is no Notifications",
          "User Profile": "User Profile",
          "Change Password": "Change Password",
          "Change Phone": "Change Phone",
          "TermsCondition": "Terms & Condition",
          "Current Password": "Current Password",
          "New Password": "New Password",
          "Confirm New Password": "Confirm New Password",
          "Save": "Save",
          "Enter Your Phone": "Enter Your Phone",
          "Next": "Next",
          "Sms Notification": "Sms Notification",
          "Normal Auctions": "Normal Auctions",
          "No Reserve Auctions": "No Reserve Auctions",
          "Buy Now Auctions": "Buy Now Auctions",
          "Out Bidding": "Out Bidding",
          "Gallery": "Gallery",
          "Camera": "Camera",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "State": "State",
          "City": "City",
          "Zip": "Zip Code",
          "Update": "Update",
          "Car details": "Car details",
          "Components Summary": "Components Summary",
          "Interior": "Interior",
          "Exterior": "Exterior",
          "For Help": "For Help",
          "PLACE A BID": "PLACE A BID",
          'Make': 'Make',
          'Model': 'Model',
          'Year': 'Year',
          'Mileage': 'Mileage',
          'Specification': 'Specification',
          'Body Type': 'Body Type',
          'Engine Size': 'Engine Size',
          'Service History': 'Service History',
          'Warranty': 'Warranty',
          'Engine Condition': 'Engine Condition',
          'Transmission': 'Transmission',
          'Mortgage': 'Mortgage',
          'Number of Keys': 'Number of Keys',
          'Central locking': 'Central locking',
          'Tires': 'Tires',
          'Steering': 'Steering',
          'Engine': 'Engine',
          'Gearbox': 'Gearbox',
          'Dash Lights': 'Dash Lights',
          'Electric Component': 'Electric Component',
          'Ac/Heating': 'Ac/Heating',
          'Breaks': 'Breaks',
          'Suspension': 'Suspension',
          'Exhaust': 'Exhaust',
          'Clutch': 'Clutch',
          'Windows Sunroof': 'Windows Sunroof',
          'Central Locking': 'Central Locking',
          'Horn Light Radio': 'Horn Light Radio',
          'Seats': 'Seats',
          'Navigation': 'Navigation',
          'Sunroof': 'Sunroof',
          'Interior Color': 'Interior Color',
          'Comment': 'Comment',
          'Front Bumper': 'Front Bumper',
          'Rear Bumper': 'Rear Bumper',
          'Bonnet': 'Bonnet',
          'Roof': 'Roof',
          'Boot Trunk': 'Boot Trunk',
          'Driver Side Front Wing': 'Driver Side Front Wing',
          'Driver Side Front Door': 'Driver Side Front Door',
          'Driver Side Rear Door': 'Driver Side Rear Door',
          'Driver Side Rear Quarter': 'Driver Side Rear Quarter',
          'Passenger Side Front Wing': 'Passenger Side Front Wing',
          'Passenger Side Front Door': 'Passenger Side Front Door',
          'Passenger Side Rear Door': 'Passenger Side Rear Door',
          'Passenger Side Rear Quarter': 'Passenger Side Rear Quarter',
          'Driver Side Front Tyre': 'Driver Side Front Tyre',
          'Driver Side Rear Tyre': 'Driver Side Rear Tyre',
          'Passenger Side Front Tyre': 'Passenger Side Front Tyre',
          'Passenger Side Rear Tyre': 'Passenger Side Rear Tyre',
          'Blue': 'Blue',
          'Faded': 'Faded',
          'Red': 'Red',
          'Painted': 'Painted',
          'White': 'White',
          'Original': 'Original',
          'Yellow': 'Yellow',
          'Smart Paint': 'Smart Paint',
          'Live Auction': 'Live Auction',
          'Auction': 'Auction',
          'CustomerPrice': 'Customer\'s Price',
          'Vat Value': 'Vat Value',
          'Starting Bid': 'Starting Bid',
          'Current Bid': 'Current Bid',
          'Total Bids': 'Total Bids',
          'Your Last Bid': 'Your Last Bid',
          'Your Last Bid': 'Your Last Bid',
          'Enter Price': 'Enter Price',
          'Clear': 'Clear',
          'PLace Bid': 'PLace Bid',
          'Bidder': 'Bidder',
          'Amount': 'Amount',
          'Time': 'Time',
          'Add Car': 'Add Car',
          'Add from Gallery': 'Add from Gallery',
          'Add from Camera': 'Add from Camera',
          'Color': 'Color',
          'Enter Car Mileage': 'Enter Car Mileage',
          'Next': 'Next',
          'Select': 'Select',
          'Type': 'Type',
          'Submit for Auction': 'Submit for Auction',
          'Live':'Live',
          'All Cars':'All Cars'
        },
      };
}


